version: "3"

services:
  CloudflareTLSDNS:
    build: ./unbound
    image: itinnovations/cloudflaretlsdns:latest
    hostname: CloudflareTLSDNS
    container_name: CloudflareTLSDNS
    image: itinnovations/cloudflaretlsdns
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 10.0.0.2

  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole:4.2.3_armhf
    restart: unless-stopped
    volumes:
      - data_1:/etc/pihole/
      - data_2:/etc/dnsmasq.d/ 
    ports:
      - "80:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - IPv6=false
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=
      - DNS1=10.0.0.2
      - DNS2=10.0.0.2
    networks:
      net:
        ipv4_address: 10.0.0.3

volumes: 
  data_1:
  data_2:

networks:
  net:
    driver: bridge
    ipam:
       config:
         - subnet: 10.0.0.0/24
